### ISSUE TITLE
Discover Granules Lambda does not support SFTP

### ISSUE THREAD

**Issue by hkryeung** [ghrcdaac/discover-granules-tf-module#64]
Noticed this module does not support SFTP yet (as compared to out of the box discover granule https://github.com/nasa/cumulus/tree/master/tasks/discover-granules)

Interesting enough it was mentioned in the source code: https://github.com/ghrcdaac/discover-granules-tf-module/blob/master/task/main.py#L22

Please consider adding SFTP support to allow some level of backward compatibility when choosing an upgraded flavor of Discover Granule

Another good to have is integrate password info inside AWS Secret Manager (exposing passwords in general in the step functions seems bad); not sure if this feature is more on Cumulu's plate but writing this down

Thanks for your time.

**Comment by amarouane-ABDELHAK** [comment]
The release v1.2.2 is supporting SFTP protocol (using username/password)
